#!/bin/bash
echo "Ultimate Geo-SEO & AEO Boilerplate - Setup Guide"
echo "================================================"
echo ""
echo "📌 Personal Access Token Setup:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name: 'ultimate-boilerplate-token'"
echo "4. Select scopes: repo, workflow, read:user"
echo "5. Click 'Generate token'"
echo "6. Copy the token (you won't see it again!)"
echo ""
echo "7. Store token locally:"
echo "   export GITHUB_TOKEN='your_token_here'"
echo ""
echo "8. Configure git:"
echo "   git config --global credential.helper store"
echo ""
echo "9. When prompted for password, use the token instead of password"
echo ""
echo "📚 Then run:"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "✅ Done! Open http://localhost:3000"
